### ISSUE TITLE
QUIT

### ISSUE THREAD

**Issue by croueAlec** [TheSecretOrganization/ft_irc#45]

**Comment by Neffi42** [comment]
**Steps to do:**

1. Acknowledge the QUIT Command: The server processes the QUIT command sent by the client, which usually includes a quit message.
2. Inform Other Clients: The server broadcasts the quit message to all other clients that share channels with the quitting client. This informs other users that the client has left the network.
3. Update Channel Membership: The server removes the client from all channels they were part of. This involves updating the channel member lists and any associated data structures.
4. Close the Client Connection: The server closes the TCP connection to the client.
5. Clean Up Resources: The server performs any necessary cleanup related to the client, such as freeing memory, removing the client from internal data structures, and logging the disconnection event if logging is enabled.
6. Propagate QUIT to Other Servers: If the IRC network consists of multiple interconnected servers, the server propagates the QUIT command to other servers in the network, ensuring all servers are aware of the client disconnection.
